CanvasPromptFont:		NetworkFont
CanvasPromptFontSize:		0.2
CanvasMinGridSpacing:		0.2
CanvasGridPointSizePixels:	0.03
CanvasFlashMessageFont:		NetworkFont
CanvasFlashMessageFontSize:	0.3

PaletteMarginInches:		0.02
ColorPaletteCellMarginInches:	0.01
ShapePaletteCellMarginInches:	0.04

BackgroundImageMaxControlSizeInches: 0.2
BackgroundImageControlSize:	1.0
BackgroundImageControlHMargin:	0.2
BackgroundImageControlVMargin:	0.3

GraphOverlayTextHMarginInches:	0.1
GraphOverlayTextVMarginInches:	0.05
GraphOverlayTextAlpha:		0.15
GraphOverlayLeftFont:		NetworkFont
GraphOverlayLeftFontSizeInches:	0.25
GraphOverlayCenterFont:		NetworkFont
GraphOverlayCenterFontSizeInches: 0.25
GraphOverlayRightFont:		BoldFont
GraphOverlayRightFontSizeInches: 0.3

GraphFootprintMinRadiusInches:	0.3
GraphFootprintMinOverviewRadiusInches:	0.1
GraphFootprintSizeScale:	1.1
GraphFootprint0Thickness:	1.0
GraphFootprint1Thickness:	0.3
GraphFootprint2Thickness:	0.11
GraphFootprint3Thickness:	0.0036

GraphDependencyExternalHeight:	0.10
GraphDependencyExternalWidth:	0.07
GraphDependencyExternalHOffset:	0.00
GraphDependencyExternalVOffset:	0.05
GraphDependencyCountMargin:	0.005
GraphDependencyCountFont:	NetworkFont
GraphDependencyCountSize:	0.14

GraphPreSelectionAlpha:		0.8            

GraphItemNameFont:		NetworkFont
GraphItemNameSize:		0.225
GraphItemDescriptionFont:	NetworkFont
GraphItemDescriptionSize:	0.2

GraphFlyoutBackgroundBlendFlagOn:	0.78
GraphFlyoutBackgroundBlendFlagOff:	0.95
GraphFlyoutOuterRadius:		0.9
GraphFlyoutInnerRadiusScale:	0.7
GraphFlyoutFlagIndicatorScale:	0.1
GraphFlyoutFlagIconScale:	0.3
GraphMinFlyoutOuterRadiusInches:0.45
GraphMinFlyoutInnerRadiusInches:0.2
GraphFlyoutRegionAlpha:		0.8
GraphFlyoutNonInteractiveAlpha:	0.4

GraphDotRadius:			0.09
GraphDotPinInnerFraction:	0.35
GraphDotPinOuterFraction:	0.65
GraphMaxDotRadiusInches:	0.1
GraphWireStubLength:		0.20
GraphWireStubRadius:		0.035
GraphWireStubSelectedBorder:	0.02
GraphWireArrowLength:		0.15
GraphWireArrowAspectRatio:	0.5
GraphWireMinArrowLengthInches:	0.05
GraphWireMaxArrowLengthInches:	0.6
GraphWireLongFadedAlpha:	0.6
GraphWireLongerFadedAlpha:	0.1
GraphWireLongFadeLength:	5.0
GraphWireLongerFadeLength:	10.0
GraphWireMinCurveRadius:	0.15
GraphWireMaxCurveRadius:	0.3
GraphWireRoundedCurveRadius:	0.3
GraphWireParmVopStubWidth:	0.2
GraphWireParmVopStubHeight:	0.1
GraphWireNodeSelectionBlend:	0.4

GraphMinConnectorSpace:		0.03
GraphConnectorRadius:		0.045
GraphConnectorPickRadius:	0.15
GraphItemCornerRadius:		0.1
GraphBorderWidth:		2
GraphHighDPIBorderWidth:	3
GraphOverviewBorderWidth:	2
GraphHighDPIOverviewBorderWidth:3

GraphCopPreviewMaxSize:		128
GraphCopPreviewMinAspect:	1.0
GraphCopPreviewMaxAspect:	5.0
GraphCopBottomBarHeight:	0.15
GraphCopBottomBarMarginLeft:	0.1
GraphCopBottomBarMarginRight:	0.1
GraphCopBottomButtonSize:	0.1
GraphCopPlaneNameFont:		InputFont

GraphVopPreviewHeight:		1.0
GraphVopConnectorHeight:	0.15
GraphVopConnectorFontHeight:	0.12
GraphVopConnectorDotScale:	0.25
GraphVopConnectorNameIndent:	0.1
GraphVopConnectorNameFont:	NetworkFont
GraphVopBottomBarHeight:	0.15
GraphVopBottomBarMarginLeft:	0.1
GraphVopBottomBarMarginRight:	0.1
GraphVopBottomButtonSize:	0.1
GraphVopBottomButtonSpacing:	0.1
GraphVopGroupExpanderWidth:	0.05
GraphVopGroupExpanderHeight:	0.08
GraphVopTopSpacing:		0.03
GraphVopBottomSpacing:		0.05
GraphVopGroupSpacing:		0.08
GraphVopFlyoutVerticalShift:	-0.1

GraphShopConnectorHeight:	0.15
GraphShopConnectorFontHeight:	0.12
GraphShopConnectorDotScale:	0.25
GraphShopConnectorNameIndent:	0.08
GraphShopConnectorNameFont:	NetworkFont
GraphShopTopSpacing:		0.03
GraphShopBottomSpacing:		0.05
GraphShopFlyoutVerticalShift:	-0.1

GraphSubnetShadowOffset:	0.0275
GraphSubnetShadowBlend1:	0.6
GraphSubnetShadowBlend2:	0.3
GraphBypassColorBlend:		0.7
GraphBypassNameColorBlend:	0.7
GraphBypassConnectorColorBlend:	0.7
GraphBypassBorderColorBlend:	0.35
GraphBypassIconAlpha:		0.4
GraphBypassBadgeAlpha:		0.4

GraphNameHSpacing:		0.1
GraphNameVSpacing:		0.06
GraphBadgeSize:			0.16
GraphBadgeDotRadius:		0.06
GraphBadgeHIndent:		0.03
GraphBadgeHSpacing:		0.22
GraphBadgeVSpacingBelow:	-0.04
GraphBadgeVSpacingAbove:	0.04
GraphNodeTypeVSpacingAbove:	0.11
GraphDescriptionVSpacingBelow:	-0.17
GraphDescriptionVSpacingBelowNoBadges:	-0.04
GraphDescriptionVSpacingAbove:	0.38
GraphDescriptionVSpacingAboveNoBadges:	0.04
GraphDescriptionWidth:		2.5
GraphDescriptionLines:		3

GraphLargeBadgeMinSizeInches:		0.3
GraphLargeBadgeOverviewMinSizeInches:	0.15
GraphLargeBadgeSize:			1.0
GraphLargeBadgeLeftShift:		-0.2
GraphLargeBadgeTopShift:		0.0
GraphLargeBadgeStackLeftShift:		-0.5
GraphLargeBadgeStackTopShift:		0.0

GraphHullOffset:		0.15
GraphHullNestedOffset:		0.05
GraphHullAlpha:			0.2

GraphPerfGlowMaxSize:		0.5
GraphPerfGlowMaxSizeInches:	0.4
GraphPerfGlowMinSizeInches:	0.1
GraphPerfGlowMaxOverviewSizeInches:	0.2
GraphPerfGlowMinOverviewSizeInches:	0.1

GraphNetworkBoxOffset:		0.15
GraphNetworkBoxMinWidth:	2.5
GraphNetworkBoxTitleHeight:	0.3
GraphNetworkBoxTitleIndent:	0.05
GraphNetworkBoxMinMaxSize:	0.25
GraphNetworkBoxMinMaxIndent:	0.05
GraphNetworkBoxAlpha:		0.5
GraphNetworkBoxTitleAlpha:	0.8
GraphNetworkBoxTitleFont:	NetworkFont
GraphNetworkBoxTitleSize:	0.225
GraphNetworkBoxEscapeVel:	5.0

GraphStickyNoteMinWidth:	2.5
GraphStickyNoteTitleHeight:	0.225
GraphStickyNoteTitleIndent:	0.05
GraphStickyNoteTextHMargin:	0.05
GraphStickyNoteTextVMargin:	0.05
GraphStickyNoteMinMaxSize:	0.25
GraphStickyNoteMinMaxIndent:	0.05
GraphStickyNoteAlpha:		0.7
GraphStickyNoteTitleAlpha:	0.9
GraphStickyNoteFont:		NetworkFont
GraphStickyNoteSize:		0.225
GraphStickyNoteTitleFont:	NetworkFont
GraphStickyNoteTitleSize:	0.225

InfoPopupBG:                    #292B35
InfoPopupNeedsRefreshBG:        #36373B
