
#include "NodeGraphCommon_qLib_190.inc"

PaletteBackground:		GREY(0.5)
PaletteSelected:		YELLOW
ShapePaletteShape:		GREY(0.2)

BackgroundImageLocate:		WHITE
BackgroundImageBorder:		YELLOW
BackgroundImageBrightness:	YELLOW
BackgroundImageLink:		GREY(0.8)

GraphOverlayLeftText:		0.2 0.9 0.9
GraphOverlayCenterText:		0.7 0.7 0.7
GraphOverlayRightText:		WHITE

GraphBackground:		GREY(0.6)
GraphOverviewBackground:	GREY(0.50)
GraphOverviewViewRegion:	0.5 0.3 0.5
GraphOverviewBorder:		GREY(0.3)
GraphPromptText:		GREY(0.1)
GraphGridLines:			GREY(0.12)
GraphGridPoints:		BLACK

GraphNameText:			GREY(0.1)
GraphNodeTypeText:		GREY(0.4)
GraphCommentText:		#88C0CC
GraphDescriptiveNameText:	#39526E
GraphContextOptionDepsText:	#236569
GraphLopLastModifiedPrimText:	#236569
GraphLopLayerCountText:		#236569
GraphOutputForViewText:		#236569
GraphDetailIdText:		            #236569
GraphNetworkBoxText:		WHITE
GraphNetworkBoxTextDark:	BLACK
GraphNetworkBoxNameText:	#76A8E1
GraphIndirectText:		WHITE
GraphIndirectTextDark:		BLACK

GraphItemBorder:		BLACK
GraphMinimizeButton:		GREY(0.8)

GraphTemplateFlag:		#DD7DD7
GraphSelectableTemplateFlag:	#B151BB
GraphBypassFlag:		#E7CD2F
GraphRenderFlag:		#A779FF
GraphDisplayFlag:		#308DFF
GraphOutputFlag:		0.75 0.4 0.0
GraphSelectableFlag:		#ABEA21
GraphExportFlag:		#FFA600
GraphHiddenFlag:		#90BECD
GraphAudioFlag:			0.0 0.5 0.5
GraphThumbnailFlag:		0.35 0.6 0.2
GraphLockFlag:			#FF 33 00
GraphSoftLockFlag:		#C4 E3 61 
GraphDebugFlag:			#6CC6B2
GraphMaterialFlag:		0.75 0.4 0.0
GraphDisplayAndRenderFlag:	0.00 0.68 0.94
GraphDisplayAndOutputFlag:	0.75 0.45 0.36
GraphFilterFlag:		#55FFC1

GraphDisplayHighlight:		#44679A
GraphExportHighlight:		#734670
GraphRenderHighlight:		#9273CB
GraphOutputHighlight:		#6B5634
GraphTemplateHighlight:		#734670
GraphFilterHighlight:		#298966

GraphDopObjectData:		GREY(0.4)
GraphDopData:			0.50	0.80	0.50
GraphDopRelData:		0.20	0.60	0.20
GraphDopSolverData:		0.35	0.25	0.45
GraphDopAnyData:		0.9	0.9	0.9
GraphSopHeightfield:		0.145 0.667 0.557
GraphSopConstraints:		0.9	0.6	0.3
GraphSopDomain:		        #6bcae2
GraphSopRestGeometry:		0.584   0.776   1.0
GraphSopCapturePose:		0.6     0.6     0.6
GraphSopAnimatedPose:		1.0     0.725   0.0

GraphConnector:			#616D76
GraphConnectorLabel:		#616D76
GraphConnectorError:		#901000
GraphCopMaskInput:		0.50 0.80 0.50
GraphWire:			#616D76
GraphWireUnused:		0.24 0.24 0.24
GraphWireError:			RED
GraphWireLoopBack:		0.3 0.3 1.0
GraphWireSelection:		#d0d000
GraphWireNodeSelection:		#800000
GraphWireLongFaded:		GREY(0.3)
GraphWireLongerFaded:		GREY(0.3)
GraphWireStub:			GREY(0.70)
GraphWireStubSelection:		YELLOW
GraphWireCut:			RED
GraphWireCutPath:		#802000 
GraphWireStitchStart:		#B8E986
GraphWireStitchEnd:		#B8E986
GraphSpareWire:			#5F31CC
GraphParmOverrideWire:		#FFA500

GraphDependency:		#EF8FA9
GraphDependencyEndAffector:	#668E4A
GraphDependencyExternalIn:	GREY(0.2)
GraphDependencyExternalOut:	GREY(0.1)

GraphPickFill:			0.9 0.9 0.9
GraphPreSelection:		0.75 0.86 1.0
GraphItemCurrent:		#FFD400
GraphItemCurrentNonSelected:	#C89C9C
GraphItemSelection:		#EEF81C
GraphItemSelectionContrast:	BLACK
GraphItemContentsSelection:	#6E780C
GraphSnapLine:			#5C704D

GraphFlyoutBackgroundFlagOn:	BLACK
GraphFlyoutBackgroundFlagOff:	BLACK
GraphFlyoutEdgeFlagOff:		GREY(0.3)
GraphFlyoutInfo:		GREY(0.1)
GraphFlyoutWarning:		0.2 0.2 0.0
GraphFlyoutError:		0.2 0.0 0.0

GraphDotPinAccent:		GREY(0.3)

GraphCopPreviewBackground:	GREY(0.1)
GraphCopBottomButtonEnabled:	GREY(0.1)

GraphVopConnectorGroupName:	WHITE
GraphVopConnectorBackground:	GREY(0.25)
GraphVopBottomButtonEnabled:	GREY(0.1)
GraphVopBottomButtonDisabled:	GREY(0.6)

GraphShopConnectorBackground:	GREY(0.1)

GraphSubnetShadow1:		BLACK
GraphSubnetShadowBlend1:	0.6
GraphSubnetShadow2:		WHITE
GraphSubnetShadowBlend2:	0.3

GraphErrorBadgeDot:		1.00 0.00 0.00
GraphChildErrorBadgeDot:	1.00 0.00 0.00
GraphWarningBadgeDot:		0.77 0.60 0.04
GraphMessageBadgeDot:		0.05 0.45 1.00
GraphCommentBadgeDot:		0.15 0.67 0.64
GraphNodeLockedBadgeDot:	1.00 0.35 0.43
GraphNodeUnloadBadgeDot:	0.60 0.65 0.73
GraphNodeHasDataBadgeDot:	0.45 0.75 0.45
GraphNeedsCookBadgeDot:		0.97 0.91 0.11
GraphHdaLockedBadgeDot:		0.43 0.47 0.48
GraphHdaUnlockedBadgeDot:	0.98 0.49 0.55
GraphHdaDelaySyncBadgeDot:	0.30 0.30 0.30
GraphTimeDependentBadgeDot:	0.72 0.91 0.53
GraphVexCachedBadgeDot:		#FF5AD2
GraphVexCachableBadgeDot:	#AA3E8C
GraphNotCompilableBadgeDot:	#E5B985
GraphConstraintsBadgeDot:	#97C473
GraphKinematicsBadgeDot:	#FF9370
GraphHasTakeDataBadgeDot:	#979797
GraphNodeUnloadBadgeDot:        #D19F9F
GraphNodeHasDataBadgeDot:       #9FABD1
Graph64bitBadgeDot:       	#AC68CC
GraphPdgDynamicBadgeDot:	#E5C8FF
GraphUnloadedPayloadsBadgeDot:	#EDC486
GraphPopulationMaskBadgeDot:	#A06B9A
GraphDiveableBadgeDot:		#73d216
GraphLoadFromDiskBadgeDot:		#dceefaff

GraphPdgProgressOutline:	WHITE
GraphPdgProgressPrecook:	#324D59
GraphPdgProgressCooking:	#B8E986
GraphPdgProgressCooked:		#4D8C2f
GraphPdgProgressWarning:	#EBF802
GraphPdgProgressError:		#FF3300
GraphPdgProgressIncomplete: #5D8642

GraphPdgProgressErrorCircle: #D0021B
GraphPdgProgressErrorFill:  #730000
GraphPdgProgressNormalFill:  #232323

GraphPdgSummaryBackground:  GREY(0.1)
GraphPdgSummaryFilterOn:    #FFD42A
GraphPdgSummaryWorkItemCooked:		#4E683F
GraphPdgSummaryWorkItemCooking:		#B8E986
GraphPdgSummaryWorkItemWaiting:		#4C564D
GraphPdgSummaryWorkItemUncooked:	GREY(0.5)
GraphPdgSummaryWorkItemFailed:		#EE5A6C
GraphPdgSummaryWorkItemCancelled:	#EBB502

GraphTaskGraphBackground:			GREY(0.1)
GraphTaskGraphBorder:				GREY(0.7)
GraphTaskGraphSeeMore:				GREY(0.9)
GraphTaskGraphWorkItemCooked:		#529232
GraphTaskGraphWorkItemCached:		#529232
GraphTaskGraphWorkItemCooking:		#ADFF49
GraphTaskGraphWorkItemWaiting:		#354B60
GraphTaskGraphWorkItemUncooked:		GREY(0.45)
GraphTaskGraphWorkItemFailed:		#FF0000
GraphTaskGraphWorkItemCancelled:	#69511B
GraphTaskGraphWorkItemSelected:		#FFD42A
GraphTaskGraphWorkItemHovered:		#33EEFF
GraphTaskGraphWorkItemAncestor:		#99FF79
GraphTaskGraphWorkItemDescendant:	#2AFFCB
GraphTaskGraphNormalWire:			GREY(0.9)
GraphTaskGraphMappedWire:			#80FFA2
GraphTaskGraphIndirectWire:			#D9DD70

GraphTaskGraphWorkItemPerfFast:     #316D09
GraphTaskGraphWorkItemPerfMed:      #E89904
GraphTaskGraphWorkItemPerfSlow:     #FF0909
GraphTaskGraphWorkItemPerfNA:		GREY(0.35)

GraphTaskGraphStatusBarFailed:	    #FF9C9C
GraphTaskGraphStatusBarCancelled:   #F7DF1B
GraphTaskGraphStatusBarCooked:	    #529232
GraphTaskGraphStatusBarCooking:	    #B7DF86
GraphTaskGraphStatusBarWaiting:	    GREY(0.6)
GraphTaskGraphStatusBarEmpty:	    GREY(0.2)

GraphTaskGraphLogError:		    #D04548
GraphTaskGraphLogWarning:	    #B8B834

GraphTaskPageRect:              #D8D8D8

GraphTopBottomButtonEnabled:	GREY(0.1)
GraphTopBottomButtonDisabled:	GREY(0.6)

GraphLopLayerOutline:		GREY(0.6)
GraphLopLayerColor1:		0.30 0.70 0.20
GraphLopLayerColor2:		0.60 0.40 0.20
GraphLopLayerColor3:		0.90 0.10 0.20
GraphLopLayerColor4:		0.30 0.20 0.30
GraphLopLayerColor5:		0.60 0.20 0.60
GraphLopLayerColor6:		0.90 0.20 0.90
GraphLopLayerColor7:		0.20 0.70 0.30
GraphLopLayerColor8:		0.20 0.40 0.60
GraphLopLayerColor9:		0.20 0.10 0.90

