
#include "NodeGraphCommon_qLib.inc"

PaletteBackground:		GREY(0.5)
PaletteSelected:		YELLOW
ShapePaletteShape:		GREY(0.15)

BackgroundImageLocate:		WHITE
BackgroundImageBorder:		YELLOW
BackgroundImageBrightness:	YELLOW
BackgroundImageLink:		GREY(0.8)

GraphOverlayLeftText:		0.2 0.9 0.9
GraphOverlayCenterText:		0.7 0.7 0.7
GraphOverlayRightText:		WHITE

GraphBackground:		GREY(0.6)
GraphOverviewBackground:	GREY(0.30)
GraphOverviewViewRegion:	0.6 0.4 0.6
GraphOverviewBorder:		GREY(0.2)
GraphPromptText:		GREY(0.1)
GraphGridLines:			GREY(0.12)
GraphGridPoints:		BLACK

GraphNameText:			GREY(0.11)
GraphNodeTypeText:		GREY(0.35)
GraphCommentText:		#335559
GraphDescriptiveNameText:	#39526E
GraphNetworkBoxText:		WHITE
GraphNetworkBoxTextDark:	BLACK
GraphIndirectText:		WHITE
GraphIndirectTextDark:		BLACK

GraphItemBorder:		BLACK
GraphMinimizeButton:		GREY(0.8)

GraphTemplateFlag:		#DD7DD7
GraphSelectableTemplateFlag:	#B151BB
GraphBypassFlag:		#E7CD2F
GraphRenderFlag:		#785D93
GraphDisplayFlag:		#6B8BAC
GraphOutputFlag:		#FF9822
GraphSelectableFlag:		#ABEA21
GraphExportFlag:		#FFA600
GraphHiddenFlag:		#90BECD
GraphAudioFlag:			0.0 0.5 0.5
GraphThumbnailFlag:		0.35 0.6 0.2
GraphLockFlag:			#FF 33 00
GraphSoftLockFlag:		#C4 E3 61 
GraphDebugFlag:			#6CC6B2
GraphMaterialFlag:		0.75 0.4 0.0
GraphDisplayAndRenderFlag:	0.00 0.68 0.94
GraphDisplayAndOutputFlag:	0.75 0.45 0.36

GraphDisplayHighlight:		#44679A
GraphExportHighlight:		#734670
GraphRenderHighlight:		#9273CB
GraphOutputHighlight:		#A16C30
GraphTemplateHighlight:		#734670

GraphDopObjectData:		0.40	0.40	0.40
GraphDopData:			0.50	0.80	0.50
GraphDopRelData:		0.20	0.60	0.20
GraphDopSolverData:		0.45	0.33	0.59
GraphDopAnyData:		0.9	0.9	0.9
GraphSopHeightfield:		0.145 0.667 0.557

GraphConnector:			#616D76
GraphCopMaskInput:		0.50 0.80 0.50
GraphWire:			#616D76
GraphWireError:			RED
GraphWireLoopBack:		0.3 0.3 1.0
GraphWireSelection:		GREEN
GraphWireNodeSelection:		0.6 0.0 0.0
GraphWireLongFaded:		0.5 0.5 0.5
GraphWireLongerFaded:		0.5 0.5 0.5
GraphWireStub:			GREY(0.30)
GraphWireStubSelection:		GREEN
GraphWireCut:			RED
GraphWireCutPath:		0.95 0.3 0.0 
GraphSpareWire:			#5F 31 CC

GraphDependency:		#EF8FA9
GraphDependencyEndAffector:	#668E4A
GraphDependencyExternalIn:	GREY(0.2)
GraphDependencyExternalOut:	GREY(0.2)

GraphPickFill:			0.9 0.9 0.9
GraphPreSelection:		0.75 0.86 1.0
GraphItemCurrent:		#FFD400
GraphItemCurrentNonSelected:	#C89C9C
GraphItemSelection:		#EEF81C
GraphItemSelectionContrast:	BLACK
GraphSnapLine:			0.25 0.45 0.25

GraphFlyoutBackgroundFlagOn:	BLACK
GraphFlyoutBackgroundFlagOff:	BLACK
GraphFlyoutEdgeFlagOff:		GREY(0.3)
GraphFlyoutInfo:		GREY(0.1)
GraphFlyoutWarning:		0.2 0.2 0.0
GraphFlyoutError:		0.2 0.0 0.0

GraphDotPinAccent:		GREY(0.3)

GraphCopPreviewBackground:	GREY(0.1)
GraphCopBottomButtonEnabled:	GREY(0.1)

GraphVopConnectorGroupName:	WHITE
GraphVopConnectorBackground:	GREY(0.45)
GraphVopBottomButtonEnabled:	GREY(0.1)
GraphVopBottomButtonDisabled:	GREY(0.6)

GraphShopConnectorBackground:	GREY(0.1)

GraphSubnetShadow1:		BLACK
GraphSubnetShadow2:		WHITE

GraphErrorBadgeDot:		1.00 0.00 0.00
GraphWarningBadgeDot:		0.77 0.60 0.04
GraphCommentBadgeDot:		0.15 0.67 0.64
GraphNodeLockedBadgeDot:	1.00 0.35 0.43
GraphNodeUnloadBadgeDot:	0.60 0.65 0.73
GraphNodeHasDataBadgeDot:	0.45 0.75 0.45
GraphHdaLockedBadgeDot:		0.43 0.47 0.48
GraphHdaUnlockedBadgeDot:	0.98 0.49 0.55
GraphTimeDependentBadgeDot:	0.72 0.91 0.53
GraphVexCachedBadgeDot:		#FF5AD2
GraphVexCachableBadgeDot:	#AA3E8C
GraphNotCompilableBadgeDot:	0.72 0.72 0.85
GraphConstraintsBadgeDot:	0.72 0.91 0.53
GraphNodeUnloadBadgeDot:        #D19F9F
GraphNodeHasDataBadgeDot:       #9FABD1

